#!/usr/local/bin/python3.6

import boto3
import json
import logging
from pprint import pprint,pformat

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def get_ecs_instances():
    logger.info("Get ECS Instances INFO")

    ecs = boto3.client('ecs')
    if not ecs:
        logger.error("ecs_error")
        return False

    clusters = ecs.list_clusters()['clusterArns']
    if not clusters:
        logger.error("No existing ECS Cluster")
        return False

    for cluster in clusters:
        cluster_ec2 = ecs.list_container_instances(cluster = cluster)['containerInstanceArns']

        cluster_ec2_detail = ecs.describe_container_instances(cluster = cluster,containerInstances = cluster_ec2)

        print("Les instances du cluster",cluster,"sont :")

        for instance in cluster_ec2_detail['containerInstances']:
            print(instance['ec2InstanceId'])

if __name__ == '__main__':
    get_ecs_instances()
